<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Web</name>
   <tag></tag>
   <elementGuidId>da640bbe-db9a-420b-b33e-28092859e8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#docsearch-hits1-item-1 > a > div.DocSearch-Hit-Container > div.DocSearch-Hit-content-wrapper > span.DocSearch-Hit-title > mark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='docsearch-hits1-item-1']/a/div/div[2]/span/mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;WebView2&quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>7dbaedd9-1dd1-48e0-92d3-4bd2be346103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Web</value>
      <webElementGuid>ed84c9e7-f6f6-4cba-973f-4eb77fe7c38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;docsearch-hits1-item-1&quot;)/a[1]/div[@class=&quot;DocSearch-Hit-Container&quot;]/div[@class=&quot;DocSearch-Hit-content-wrapper&quot;]/span[@class=&quot;DocSearch-Hit-title&quot;]/mark[1]</value>
      <webElementGuid>abace86f-9280-43d5-a07b-cab181ffef5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='docsearch-hits1-item-1']/a/div/div[2]/span/mark</value>
      <webElementGuid>ad3f2522-3e34-4c86-baec-0da011675a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guides'])[1]/following::mark[1]</value>
      <webElementGuid>ffca315b-3a52-4b35-b187-ad541a1930d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web'])[2]/preceding::mark[1]</value>
      <webElementGuid>70b0ec7a-4a17-4ae0-b080-ec6ee0654a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Web']/parent::*</value>
      <webElementGuid>90469962-781c-46e8-b7b6-aff0e3527f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/ul/li/a/div/div[2]/span/mark</value>
      <webElementGuid>fc72e99e-42be-4208-9fed-9395988460bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'Web' or . = 'Web')]</value>
      <webElementGuid>2eead09f-7b67-45d0-950b-9c4b64db3693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
