<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>c3c74a73-38a6-4ae1-aad7-b7c0e8d9c798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.DocSearch-Button-Placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus']/nav/div/div[2]/div[2]/button/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search (Ctrl+K)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a7ba79f1-1447-4f53-a9be-53823e6c609f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DocSearch-Button-Placeholder</value>
      <webElementGuid>954859c2-a5e7-4942-893e-6d248c8c73a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>07a22579-63eb-4ad9-872a-2018f0c1c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus&quot;)/nav[@class=&quot;navbar navbar--fixed-top&quot;]/div[@class=&quot;navbar__inner&quot;]/div[@class=&quot;navbar__items navbar__items--right&quot;]/div[@class=&quot;navbarSearchContainer_Bca1&quot;]/button[@class=&quot;DocSearch DocSearch-Button&quot;]/span[@class=&quot;DocSearch-Button-Container&quot;]/span[@class=&quot;DocSearch-Button-Placeholder&quot;]</value>
      <webElementGuid>91833020-0a0e-4c5c-9469-63aab6d66ed1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus']/nav/div/div[2]/div[2]/button/span/span</value>
      <webElementGuid>3eee0731-43f3-47e3-b3e5-d5d5d97c5f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Community'])[1]/following::span[2]</value>
      <webElementGuid>68a87c40-2704-4f72-b2fc-838b5360892e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.NET'])[1]/following::span[2]</value>
      <webElementGuid>dcd3a7ef-4144-4356-a13a-dd0efb39dfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='K'])[1]/preceding::span[1]</value>
      <webElementGuid>0c7eca94-7254-46b9-8c16-ddbb0aaf4cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation'])[1]/preceding::span[2]</value>
      <webElementGuid>c33e50ec-8848-4985-94be-1c5e3f7e7981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>46938a70-3275-4018-84a5-2ff4817997fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>9c93f72b-1614-4c31-9d7a-4c684b3956bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>1d1c96ff-6a0c-4800-9780-52fdd1f34ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
